version: "2"
run:
  go: "1.24"
linters:
  enable:
    - gocritic
    - misspell
    - revive
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/dminnear-rh/patternizer
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
